import type { ProductLang } from "./AutomationProductPage";

type Copy = Parameters<typeof import("./AutomationProductPage").default>[0]["copy"];

export const finopsContent: Record<ProductLang, Copy> = {
  en: {
    languageName:"English", eyebrow:"AWS Cloud · FinOps", title:"AWS Cost Optimization Assessment", tagline:"Understand where your AWS money goes, identify avoidable spend, and leave with a prioritized plan your team can actually implement.",
    demoTitle:"Assessment walkthrough", demoText:"The final demo will show how Lumbe Tech reviews cost drivers, architecture and usage signals, turns findings into priorities, and separates quick wins from changes that need engineering work.",
    problemTitle:"The business problem", problem:"AWS spend can grow faster than visibility. Oversized compute, idle resources, NAT and data-transfer patterns, storage choices, always-on non-production environments and architecture decisions can all add cost without creating equivalent business value. A lower bill is useful only when optimization does not compromise reliability or security.",
    worksTitle:"How the assessment works", steps:["We establish scope, business constraints and the AWS environments that should be reviewed.","We analyze the main cost drivers and relate them to how the workloads are actually designed and operated.","We look for optimization opportunities across compute, storage, networking, managed services, scaling and non-production usage, rather than applying generic cost-cutting rules.","Each validated finding is classified by expected value, implementation effort, operational risk and priority.","You receive a concise remediation roadmap separating quick wins from architectural changes and longer-term FinOps controls.","Implementation can be scoped separately. Your team can also execute the roadmap without being locked into Lumbe Tech."],
    whyTitle:"Why implement it", why:"A cost review creates a shared view of spend for engineering and business stakeholders. Instead of cutting resources blindly, the goal is to remove waste while preserving the capacity, resilience and security the workload actually needs.",
    impactTitle:"Potential business impact", impact:"The expected impact is better cost visibility, fewer unnecessary resources, clearer ownership of recurring cloud spend and a prioritized optimization backlog. Savings are not promised as a generic percentage: the opportunity is quantified only after the customer environment and usage are reviewed.",
    controlTitle:"Engineering evidence behind the service", control:"The assessment is grounded in infrastructure patterns already implemented by Lumbe Tech: Terraform-based AWS environments, EKS cost analysis, KEDA scale-to-zero, serverless operations, CloudWatch visibility and explicit analysis of NAT Gateway, load balancer, compute and control-plane costs. Recommendations are tied to the customer's workload, not copied from a checklist.",
    docsTitle:"Assessment deliverables", docsIntro:"The engagement is designed to end with usable engineering decisions, not a long generic report.", docsStatus:"Included", docs:[{title:"Cost Findings Register",text:"Validated findings with affected service or architecture area, evidence, priority and recommended action."},{title:"Optimization Roadmap",text:"Quick wins, engineering changes and longer-term controls ordered by value, effort and risk."},{title:"Executive Summary",text:"A concise business-facing view of major cost drivers, opportunities, assumptions and next steps."}],
    ctaTitle:"Start with your AWS bill", ctaText:"We first confirm account scope, workload context and the cost areas that matter. Then we define a fixed-scope assessment around your environment.", cta:"Discuss your AWS spend", back:"Back to solutions"
  },
  pt: {
    languageName:"Português", eyebrow:"AWS Cloud · FinOps", title:"Avaliação de Otimização de Custos AWS", tagline:"Entenda para onde vai o dinheiro na AWS, identifique gastos evitáveis e receba um plano priorizado que a sua equipa consegue executar.",
    demoTitle:"Demonstração da avaliação", demoText:"A demo final mostrará como a Lumbe Tech analisa os principais custos, arquitetura e sinais de utilização, transforma achados em prioridades e separa ganhos rápidos de mudanças que exigem engenharia.",
    problemTitle:"O problema empresarial", problem:"Os custos AWS podem crescer mais depressa do que a visibilidade. Compute sobredimensionado, recursos ociosos, padrões de NAT e transferência de dados, escolhas de storage, ambientes não produtivos sempre ligados e decisões de arquitetura podem aumentar a fatura sem gerar valor equivalente. Reduzir custos só faz sentido quando não compromete fiabilidade ou segurança.",
    worksTitle:"Como funciona a avaliação", steps:["Definimos o escopo, restrições do negócio e os ambientes AWS que devem ser analisados.","Analisamos os principais drivers de custo e relacionamo-los com a forma como os workloads são desenhados e operados.","Procuramos oportunidades em compute, storage, networking, serviços geridos, scaling e ambientes não produtivos, sem aplicar cortes genéricos.","Cada achado validado é classificado por valor esperado, esforço de implementação, risco operacional e prioridade.","Entregamos um roadmap conciso que separa quick wins, mudanças arquiteturais e controlos FinOps de longo prazo.","A implementação pode ser contratada separadamente; a equipa do cliente também pode executar o roadmap sem ficar presa à Lumbe Tech."],
    whyTitle:"Por que implementar", why:"A avaliação cria uma visão comum dos custos para engenharia e negócio. Em vez de desligar recursos às cegas, o objetivo é remover desperdício preservando capacidade, resiliência e segurança realmente necessárias.",
    impactTitle:"Impacto potencial no negócio", impact:"O impacto esperado é maior visibilidade de custos, menos recursos desnecessários, responsabilidade mais clara sobre gastos recorrentes e um backlog de otimização priorizado. Não prometemos uma percentagem genérica de poupança: a oportunidade é quantificada apenas depois de analisar o ambiente e a utilização do cliente.",
    controlTitle:"Base técnica do serviço", control:"A avaliação apoia-se em padrões que a Lumbe Tech já implementou: infraestrutura AWS com Terraform, análise de custos EKS, scale-to-zero com KEDA, operações serverless, visibilidade CloudWatch e análise explícita de custos de NAT Gateway, load balancers, compute e control plane. As recomendações são ligadas ao workload do cliente, não copiadas de uma checklist.",
    docsTitle:"Entregáveis da avaliação", docsIntro:"O engagement termina com decisões de engenharia utilizáveis, não com um relatório genérico de dezenas de páginas.", docsStatus:"Incluído", docs:[{title:"Registo de Achados de Custo",text:"Achados validados com serviço ou área afetada, evidência, prioridade e ação recomendada."},{title:"Roadmap de Otimização",text:"Quick wins, mudanças de engenharia e controlos de longo prazo ordenados por valor, esforço e risco."},{title:"Resumo Executivo",text:"Visão concisa dos principais drivers de custo, oportunidades, pressupostos e próximos passos."}],
    ctaTitle:"Comece pela sua fatura AWS", ctaText:"Primeiro confirmamos o escopo das contas, contexto dos workloads e áreas de custo relevantes. Depois definimos uma avaliação de escopo fixo para o seu ambiente.", cta:"Falar sobre os custos AWS", back:"Voltar às soluções"
  },
  fr: {
    languageName:"Français", eyebrow:"AWS Cloud · FinOps", title:"Évaluation d'optimisation des coûts AWS", tagline:"Comprenez où part votre budget AWS, identifiez les dépenses évitables et repartez avec un plan priorisé que votre équipe peut réellement exécuter.",
    demoTitle:"Présentation de l'évaluation", demoText:"La démonstration finale montrera comment Lumbe Tech analyse les principaux postes de coût, l'architecture et l'utilisation, puis transforme les constats en priorités et distingue les gains rapides des changements d'ingénierie.",
    problemTitle:"Le problème métier", problem:"Les dépenses AWS peuvent croître plus vite que leur visibilité. Compute surdimensionné, ressources inactives, NAT et transferts de données, choix de stockage, environnements hors production toujours actifs et décisions d'architecture peuvent augmenter la facture sans valeur équivalente. Réduire la facture n'a de sens que sans sacrifier fiabilité ou sécurité.",
    worksTitle:"Comment fonctionne l'évaluation", steps:["Nous définissons le périmètre, les contraintes métier et les environnements AWS à examiner.","Nous analysons les principaux moteurs de coût et les relions à la conception et à l'exploitation réelles des workloads.","Nous recherchons des opportunités sur le compute, le stockage, le réseau, les services managés, le scaling et les environnements hors production, sans appliquer de règles génériques.","Chaque constat validé est classé selon sa valeur attendue, l'effort d'implémentation, le risque opérationnel et la priorité.","Vous recevez une feuille de route concise séparant gains rapides, changements d'architecture et contrôles FinOps à plus long terme.","L'implémentation peut être cadrée séparément ; votre équipe peut aussi exécuter la feuille de route sans dépendance à Lumbe Tech."],
    whyTitle:"Pourquoi l'implémenter", why:"L'évaluation donne une vision commune des coûts aux équipes techniques et métier. L'objectif n'est pas de couper aveuglément, mais de supprimer le gaspillage tout en conservant capacité, résilience et sécurité nécessaires.",
    impactTitle:"Impact potentiel", impact:"L'impact attendu est une meilleure visibilité des coûts, moins de ressources inutiles, une responsabilité plus claire sur les dépenses récurrentes et un backlog d'optimisation priorisé. Aucun pourcentage générique d'économie n'est promis : l'opportunité est quantifiée après examen de l'environnement et de l'utilisation réels.",
    controlTitle:"Preuves d'ingénierie derrière le service", control:"L'évaluation s'appuie sur des patterns déjà implémentés par Lumbe Tech : environnements AWS Terraform, analyse de coûts EKS, scale-to-zero avec KEDA, opérations serverless, visibilité CloudWatch et analyse explicite des coûts NAT Gateway, load balancer, compute et control plane. Les recommandations sont liées au workload du client.",
    docsTitle:"Livrables de l'évaluation", docsIntro:"La mission se termine par des décisions d'ingénierie exploitables, pas par un long rapport générique.", docsStatus:"Inclus", docs:[{title:"Registre des constats de coût",text:"Constats validés avec service ou zone concernée, preuve, priorité et action recommandée."},{title:"Feuille de route d'optimisation",text:"Gains rapides, changements d'ingénierie et contrôles de long terme ordonnés par valeur, effort et risque."},{title:"Synthèse exécutive",text:"Vue concise des principaux moteurs de coût, opportunités, hypothèses et prochaines étapes."}],
    ctaTitle:"Commencez par votre facture AWS", ctaText:"Nous confirmons d'abord le périmètre des comptes, le contexte des workloads et les postes de coût importants, puis cadrons une évaluation à périmètre fixe.", cta:"Discuter de vos coûts AWS", back:"Retour aux solutions"
  },
  es: {
    languageName:"Español", eyebrow:"AWS Cloud · FinOps", title:"Evaluación de optimización de costes AWS", tagline:"Entiende dónde se va tu presupuesto AWS, identifica gasto evitable y recibe un plan priorizado que tu equipo pueda ejecutar.",
    demoTitle:"Recorrido de la evaluación", demoText:"La demo final mostrará cómo Lumbe Tech revisa los principales costes, arquitectura y señales de uso, convierte hallazgos en prioridades y separa quick wins de cambios que requieren ingeniería.",
    problemTitle:"El problema empresarial", problem:"El gasto AWS puede crecer más rápido que su visibilidad. Compute sobredimensionado, recursos inactivos, patrones de NAT y transferencia, decisiones de almacenamiento, entornos no productivos siempre encendidos y decisiones de arquitectura pueden aumentar la factura sin valor equivalente. Reducir costes solo es útil si no compromete fiabilidad o seguridad.",
    worksTitle:"Cómo funciona la evaluación", steps:["Definimos alcance, restricciones del negocio y los entornos AWS que deben revisarse.","Analizamos los principales drivers de coste y los relacionamos con el diseño y operación reales de los workloads.","Buscamos oportunidades en compute, almacenamiento, red, servicios gestionados, escalado y uso no productivo, sin aplicar recortes genéricos.","Cada hallazgo validado se clasifica por valor esperado, esfuerzo, riesgo operativo y prioridad.","Entregamos un roadmap conciso que separa quick wins, cambios arquitectónicos y controles FinOps a largo plazo.","La implementación puede contratarse aparte; el equipo del cliente también puede ejecutar el roadmap sin dependencia de Lumbe Tech."],
    whyTitle:"Por qué implementarlo", why:"La evaluación crea una visión compartida del gasto entre ingeniería y negocio. El objetivo no es apagar recursos a ciegas, sino eliminar desperdicio conservando capacidad, resiliencia y seguridad necesarias.",
    impactTitle:"Impacto potencial", impact:"El impacto esperado es mayor visibilidad de costes, menos recursos innecesarios, responsabilidad más clara sobre gasto recurrente y un backlog de optimización priorizado. No prometemos un porcentaje genérico de ahorro: la oportunidad se cuantifica después de revisar el entorno y uso reales.",
    controlTitle:"Evidencia técnica detrás del servicio", control:"La evaluación se apoya en patrones ya implementados por Lumbe Tech: entornos AWS con Terraform, análisis de costes EKS, scale-to-zero con KEDA, operaciones serverless, visibilidad CloudWatch y análisis explícito de NAT Gateway, load balancers, compute y control plane. Las recomendaciones se vinculan al workload del cliente.",
    docsTitle:"Entregables de la evaluación", docsIntro:"El engagement termina con decisiones de ingeniería utilizables, no con un informe genérico interminable.", docsStatus:"Incluido", docs:[{title:"Registro de Hallazgos de Coste",text:"Hallazgos validados con servicio o área afectada, evidencia, prioridad y acción recomendada."},{title:"Roadmap de Optimización",text:"Quick wins, cambios de ingeniería y controles a largo plazo ordenados por valor, esfuerzo y riesgo."},{title:"Resumen Ejecutivo",text:"Vista concisa de los principales drivers de coste, oportunidades, supuestos y próximos pasos."}],
    ctaTitle:"Empieza por tu factura AWS", ctaText:"Primero confirmamos el alcance de cuentas, contexto de workloads y áreas de coste relevantes. Después definimos una evaluación de alcance fijo para tu entorno.", cta:"Hablar sobre costes AWS", back:"Volver a soluciones"
  }
};

export const securityContent: Record<ProductLang, Copy> = {
  en: {
    languageName:"English", eyebrow:"AWS Cloud · Security", title:"AWS Security & Cloud Posture Assessment", tagline:"Find risky AWS configurations, missing controls and unnecessary exposure, then turn the findings into a prioritized remediation plan.",
    demoTitle:"Security assessment walkthrough", demoText:"The final demo will show the assessment method, example evidence, severity-based prioritization and how findings become a remediation roadmap without exposing customer data or credentials.",
    problemTitle:"The business problem", problem:"Cloud security gaps are often ordinary configuration problems rather than exotic attacks: permissions broader than necessary, public exposure, weak logging, unmanaged secrets, missing encryption or backups, and security services that are absent or poorly configured. Teams need a clear view of what matters first.",
    worksTitle:"How the assessment works", steps:["We agree the AWS scope, access method and business-critical workloads before reviewing anything.","We review identity and access, network exposure, encryption, secrets handling, logging and auditability, backup coverage and relevant security services.","Where applicable, evidence from services such as Security Hub, GuardDuty, IAM Access Analyzer, AWS Config and CloudTrail is incorporated into the review.","Findings are validated in context and classified by severity, affected area and remediation priority rather than treated as an undifferentiated scanner output.","You receive a prioritized remediation roadmap with concrete next steps and dependencies.","Remediation can be scoped separately, or your internal team can use the deliverables directly."],
    whyTitle:"Why implement it", why:"The assessment gives technical and business stakeholders a shared picture of AWS security posture. It helps focus limited engineering time on the exposures and missing controls that deserve attention first instead of treating every finding as equally urgent.",
    impactTitle:"Potential business impact", impact:"The expected impact is clearer risk visibility, fewer avoidable misconfigurations, stronger auditability and a practical remediation backlog. The assessment does not claim to certify the environment or guarantee the absence of vulnerabilities; formal compliance or penetration testing requires its own scope where applicable.",
    controlTitle:"Engineering evidence behind the service", control:"Lumbe Tech's reference AWS infrastructure implements defense-in-depth controls including WAF, GuardDuty, Security Hub, IAM Access Analyzer, AWS Config, CloudTrail, VPC Flow Logs, KMS, Secrets Manager, backups and GitHub Actions OIDC. That implementation experience informs the assessment while recommendations remain specific to the customer's architecture and requirements.",
    docsTitle:"Assessment deliverables", docsIntro:"The output is designed for remediation and decision-making, with evidence and clear boundaries around what was assessed.", docsStatus:"Included", docs:[{title:"Security Findings Register",text:"Evidence-backed findings with severity, affected area, rationale and recommended remediation."},{title:"Prioritized Remediation Roadmap",text:"Actions ordered by risk, dependency and implementation effort so the team knows what to address first."},{title:"Executive Security Summary",text:"Concise posture summary, assessment scope, key risks, limitations and recommended next steps."}],
    ctaTitle:"Get a clearer view of your AWS risk", ctaText:"We first define account scope, critical workloads and the access model. Then we propose a fixed-scope assessment with explicit boundaries and deliverables.", cta:"Discuss a security assessment", back:"Back to solutions"
  },
  pt: {
    languageName:"Português", eyebrow:"AWS Cloud · Segurança", title:"Avaliação de Segurança e Postura Cloud AWS", tagline:"Identifique configurações arriscadas, controlos em falta e exposição desnecessária na AWS e transforme os achados num plano de remediação priorizado.",
    demoTitle:"Demonstração da avaliação de segurança", demoText:"A demo final mostrará o método de avaliação, exemplos de evidência, priorização por severidade e como os achados se transformam num roadmap sem expor dados ou credenciais de clientes.",
    problemTitle:"O problema empresarial", problem:"Falhas de segurança cloud são muitas vezes problemas comuns de configuração: permissões mais amplas do que o necessário, exposição pública, logging insuficiente, secrets mal geridos, ausência de encryption ou backups e serviços de segurança ausentes ou mal configurados. A equipa precisa saber o que corrigir primeiro.",
    worksTitle:"Como funciona a avaliação", steps:["Acordamos o escopo AWS, método de acesso e workloads críticos antes de qualquer revisão.","Revemos identidade e acessos, exposição de rede, encryption, gestão de secrets, logging e auditabilidade, backups e serviços de segurança relevantes.","Quando aplicável, incorporamos evidências de Security Hub, GuardDuty, IAM Access Analyzer, AWS Config e CloudTrail.","Os achados são validados no contexto e classificados por severidade, área afetada e prioridade de remediação, em vez de serem tratados como simples output de scanner.","Entregamos um roadmap priorizado com próximos passos concretos e dependências.","A remediação pode ser contratada separadamente ou executada diretamente pela equipa interna com os entregáveis."],
    whyTitle:"Por que implementar", why:"A avaliação dá aos stakeholders técnicos e de negócio uma visão comum da postura de segurança AWS. Ajuda a concentrar o tempo de engenharia nas exposições e controlos em falta que merecem atenção primeiro.",
    impactTitle:"Impacto potencial no negócio", impact:"O impacto esperado é maior visibilidade de risco, menos configurações evitavelmente inseguras, melhor auditabilidade e um backlog prático de remediação. A avaliação não certifica o ambiente nem garante ausência de vulnerabilidades; compliance formal ou penetration testing exigem escopo próprio quando aplicável.",
    controlTitle:"Base técnica do serviço", control:"A infraestrutura AWS de referência da Lumbe Tech implementa WAF, GuardDuty, Security Hub, IAM Access Analyzer, AWS Config, CloudTrail, VPC Flow Logs, KMS, Secrets Manager, backups e GitHub Actions OIDC. Essa experiência informa a avaliação, mas as recomendações são específicas à arquitetura e requisitos do cliente.",
    docsTitle:"Entregáveis da avaliação", docsIntro:"A saída é desenhada para remediação e tomada de decisão, com evidências e limites claros sobre o que foi avaliado.", docsStatus:"Incluído", docs:[{title:"Registo de Achados de Segurança",text:"Achados sustentados por evidências com severidade, área afetada, justificação e remediação recomendada."},{title:"Roadmap de Remediação",text:"Ações ordenadas por risco, dependências e esforço para a equipa saber o que tratar primeiro."},{title:"Resumo Executivo de Segurança",text:"Resumo conciso da postura, escopo avaliado, riscos principais, limitações e próximos passos."}],
    ctaTitle:"Tenha uma visão mais clara do risco AWS", ctaText:"Primeiro definimos escopo das contas, workloads críticos e modelo de acesso. Depois propomos uma avaliação de escopo fixo com limites e entregáveis explícitos.", cta:"Falar sobre a avaliação", back:"Voltar às soluções"
  },
  fr: {
    languageName:"Français", eyebrow:"AWS Cloud · Sécurité", title:"Évaluation sécurité et posture cloud AWS", tagline:"Identifiez les configurations AWS risquées, les contrôles manquants et les expositions inutiles, puis transformez les constats en plan de remédiation priorisé.",
    demoTitle:"Présentation de l'évaluation sécurité", demoText:"La démonstration finale montrera la méthode d'évaluation, des exemples de preuves, la priorisation par sévérité et la transformation des constats en feuille de route sans exposer données ni identifiants client.",
    problemTitle:"Le problème métier", problem:"Les failles cloud sont souvent des problèmes de configuration ordinaires : permissions trop larges, exposition publique, journalisation insuffisante, secrets mal gérés, chiffrement ou sauvegardes manquants, services de sécurité absents ou mal configurés. L'équipe doit savoir quoi corriger en premier.",
    worksTitle:"Comment fonctionne l'évaluation", steps:["Nous convenons du périmètre AWS, du mode d'accès et des workloads critiques avant toute revue.","Nous examinons identités et accès, exposition réseau, chiffrement, gestion des secrets, logs et auditabilité, sauvegardes et services de sécurité pertinents.","Lorsque pertinent, les preuves issues de Security Hub, GuardDuty, IAM Access Analyzer, AWS Config et CloudTrail sont intégrées à l'analyse.","Les constats sont validés dans leur contexte et classés par sévérité, zone affectée et priorité de remédiation plutôt que traités comme une simple sortie de scanner.","Vous recevez une feuille de route priorisée avec actions concrètes et dépendances.","La remédiation peut être cadrée séparément ou réalisée directement par votre équipe à partir des livrables."],
    whyTitle:"Pourquoi l'implémenter", why:"L'évaluation donne aux parties prenantes techniques et métier une vision commune de la posture sécurité AWS. Elle concentre le temps d'ingénierie sur les expositions et contrôles manquants qui méritent l'attention en premier.",
    impactTitle:"Impact potentiel", impact:"L'impact attendu est une meilleure visibilité du risque, moins de mauvaises configurations évitables, une auditabilité renforcée et un backlog de remédiation pratique. L'évaluation ne certifie pas l'environnement et ne garantit pas l'absence de vulnérabilités ; conformité formelle ou test d'intrusion nécessitent un périmètre dédié.",
    controlTitle:"Preuves d'ingénierie derrière le service", control:"L'infrastructure AWS de référence de Lumbe Tech implémente WAF, GuardDuty, Security Hub, IAM Access Analyzer, AWS Config, CloudTrail, VPC Flow Logs, KMS, Secrets Manager, sauvegardes et GitHub Actions OIDC. Cette expérience nourrit l'évaluation, tandis que les recommandations restent spécifiques à l'architecture du client.",
    docsTitle:"Livrables de l'évaluation", docsIntro:"La sortie est conçue pour la remédiation et la décision, avec des preuves et des limites claires sur le périmètre évalué.", docsStatus:"Inclus", docs:[{title:"Registre des constats sécurité",text:"Constats étayés avec sévérité, zone affectée, justification et remédiation recommandée."},{title:"Feuille de route de remédiation",text:"Actions ordonnées par risque, dépendances et effort pour savoir quoi traiter en premier."},{title:"Synthèse sécurité exécutive",text:"Résumé concis de la posture, du périmètre, des principaux risques, limites et prochaines étapes."}],
    ctaTitle:"Obtenez une vision plus claire de votre risque AWS", ctaText:"Nous définissons d'abord le périmètre des comptes, les workloads critiques et le modèle d'accès, puis proposons une évaluation à périmètre fixe.", cta:"Discuter d'une évaluation sécurité", back:"Retour aux solutions"
  },
  es: {
    languageName:"Español", eyebrow:"AWS Cloud · Seguridad", title:"Evaluación de seguridad y postura cloud AWS", tagline:"Identifica configuraciones AWS de riesgo, controles ausentes y exposición innecesaria, y convierte los hallazgos en un plan de remediación priorizado.",
    demoTitle:"Recorrido de la evaluación de seguridad", demoText:"La demo final mostrará el método de evaluación, ejemplos de evidencia, priorización por severidad y cómo los hallazgos se convierten en un roadmap sin exponer datos ni credenciales del cliente.",
    problemTitle:"El problema empresarial", problem:"Las brechas de seguridad cloud suelen ser problemas de configuración comunes: permisos demasiado amplios, exposición pública, logging insuficiente, secretos mal gestionados, falta de cifrado o backups y servicios de seguridad ausentes o mal configurados. El equipo necesita saber qué corregir primero.",
    worksTitle:"Cómo funciona la evaluación", steps:["Acordamos alcance AWS, método de acceso y workloads críticos antes de revisar nada.","Revisamos identidad y acceso, exposición de red, cifrado, gestión de secretos, logging y auditabilidad, backups y servicios de seguridad relevantes.","Cuando aplica, incorporamos evidencia de Security Hub, GuardDuty, IAM Access Analyzer, AWS Config y CloudTrail.","Los hallazgos se validan en contexto y se clasifican por severidad, área afectada y prioridad de remediación en lugar de tratarse como simple salida de scanner.","Entregamos un roadmap priorizado con próximos pasos concretos y dependencias.","La remediación puede contratarse aparte o ejecutarse directamente por el equipo interno usando los entregables."],
    whyTitle:"Por qué implementarlo", why:"La evaluación da a los stakeholders técnicos y de negocio una visión compartida de la postura de seguridad AWS. Ayuda a concentrar el tiempo de ingeniería en las exposiciones y controles ausentes que merecen atención primero.",
    impactTitle:"Impacto potencial", impact:"El impacto esperado es mayor visibilidad del riesgo, menos configuraciones inseguras evitables, mejor auditabilidad y un backlog práctico de remediación. La evaluación no certifica el entorno ni garantiza ausencia de vulnerabilidades; cumplimiento formal o pentesting requieren su propio alcance cuando aplique.",
    controlTitle:"Evidencia técnica detrás del servicio", control:"La infraestructura AWS de referencia de Lumbe Tech implementa WAF, GuardDuty, Security Hub, IAM Access Analyzer, AWS Config, CloudTrail, VPC Flow Logs, KMS, Secrets Manager, backups y GitHub Actions OIDC. Esa experiencia informa la evaluación, mientras las recomendaciones siguen siendo específicas a la arquitectura del cliente.",
    docsTitle:"Entregables de la evaluación", docsIntro:"La salida está diseñada para remediación y toma de decisiones, con evidencia y límites claros sobre lo evaluado.", docsStatus:"Incluido", docs:[{title:"Registro de Hallazgos de Seguridad",text:"Hallazgos respaldados por evidencia con severidad, área afectada, justificación y remediación recomendada."},{title:"Roadmap de Remediación",text:"Acciones ordenadas por riesgo, dependencias y esfuerzo para que el equipo sepa qué abordar primero."},{title:"Resumen Ejecutivo de Seguridad",text:"Resumen conciso de postura, alcance, riesgos principales, limitaciones y próximos pasos."}],
    ctaTitle:"Obtén una visión más clara del riesgo AWS", ctaText:"Primero definimos alcance de cuentas, workloads críticos y modelo de acceso. Después proponemos una evaluación de alcance fijo con límites y entregables explícitos.", cta:"Hablar sobre la evaluación", back:"Volver a soluciones"
  }
};
